#!/bin/bash

echo "================================================================"
echo "Veyon Screen Recording Permission Helper"
echo "================================================================"
echo ""
echo "This script will help grant Screen Recording permissions to veyon-server."
echo ""
echo "STEPS:"
echo "1. Open System Preferences > Security & Privacy > Privacy > Screen Recording"
echo "2. Click the lock icon to make changes (you'll need your password)"
echo "3. Click the '+' button"
echo "4. Navigate to and select:"
echo "   /Users/pablo/GitHub/veyon/dist/bin/veyon-server"
echo "5. Make sure the checkbox next to veyon-server is CHECKED"
echo ""
echo "ALTERNATIVE (easier):"
echo "Run veyon-server once - it will trigger a permission prompt:"
echo ""
echo "   ./dist/bin/veyon-server"
echo ""
echo "Then go to System Preferences and approve it."
echo ""
echo "================================================================"
echo ""
echo "Press Enter to open System Preferences > Security & Privacy..."
read

open "x-apple.systempreferences:com.apple.preference.security?Privacy_ScreenCapture"

echo ""
echo "After granting permissions, you can test with:"
echo "   ./dist/bin/veyon-service"
echo ""
